server:
  port: 8082

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-database